env:
  TERM: alacritty

window:
  startup_mode: Maximized

  title: Alacritty

  dynamic_title: true

  padding:
    x: 0
    y: 0

  opacity: 0.8

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: JetBrains Mono Nerd Font
    style:  Medium

  bold:
    family: JetBrains Mono Nerd Font
    style:  Bold

  italic:
    family: JetBrains Mono Nerd Font
    style:  MediumItalic

  bold_italic:
    family: JetBrains Mono Nerd Font
    style:  BoldItalic

  size: 14

  draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x282828'
    foreground: '0xebdbb2'

  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
